command_timeout = 1999
add_newline = false
format = '$username$hostname$directory${custom.wsl}$all'

[conda]
symbol = "venv:"
style = "bold blue"
ignore_base = false

[username]
disabled = true

[battery]
disabled = true

[hostname]
ssh_only = false
disabled = false

[nodejs]
symbol = "â¬¢ "

[git_branch]
disabled = true
[git_commit]
disabled = true
[git_state]
disabled = true
[git_status]
disabled = true

[custom.wsl]
os = "linux"
command = "printf '%s' '(WSL)'"
shell = ["sh"]
when = "test -n $WSL_DISTRO_NAME"
format = "[$output]($style) "
style = "purple"

[custom.jj]
#command = "jj-starship"
when = "jj-starship detect"
shell = ["jj-starship"]
format = "$output "
use_stdin = true
