command_timeout = 1999
add_newline = false
format = '$username$hostname${custom.wsl}$shell$directory$all'

[conda]
symbol = "venv:"
style = "bold blue"
ignore_base = false

[username]
disabled = true

[battery]
disabled = true

[directory]
format = " in [$path]($style)[$read_only]($read_only_style) "

[hostname]
disabled = false
ssh_only = false
format = "[$hostname]($style)"

[nodejs]
symbol = "â¬¢ "

[git_branch]
disabled = true
[git_commit]
disabled = true
[git_state]
disabled = true
[git_status]
disabled = true

[pijul_channel]
disabled = true

[shell]
disabled = false
format = " [$indicator]($style)"
style = "blue"

[custom.wsl]
os = "linux"
command = "printf '(WSL)'"
shell = ["sh"]
when = 'test -n "$WSL_DISTRO_NAME"'
format = "[$output]($style)"
style = "purple"

[custom.jj]
#command = "jj-starship"
when = "jj-starship detect"
shell = ["jj-starship"]
format = "$output "
use_stdin = true
