# Reference: https://pixi.sh/latest/reference/pixi_configuration/
[shell]
change-ps1 = false

[mirrors]
"https://conda.anaconda.org/conda-forge" = [
    "https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge",
    "https://mirror.nju.edu.cn/anaconda/cloud/conda-forge",
    "https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge"
]

[repodata-config]
disable-jlap = true
disable-zstd = true

[pypi-config]
index-url = "https://mirrors.ustc.edu.cn/pypi/simple/"
